# SPDX-License-Identifier: MPL-2.0
"""Writes ontology/catalog-v001.xml, the OASIS XML catalog Protégé and the OWL
API read from the directory of the ontology they open.

It maps each Open CBAA ontology IRI to its file here, and each released
LATTICE ontology version IRI to the raw file at its release tag, read from
LATTICE's release register. An ontology's own (unversioned) IRI maps to its
latest release, since some LATTICE documents import one that way. External
vocabularies LATTICE imports (PROV-O, SKOS, SHACL, SWRL) are mapped as
LATTICE's own catalog maps them. LATTICE tooling (compilers, checks) still
needs a checkout of LATTICE.

Usage::

    python tools/lattice_catalog.py [--register URL-or-path]
"""

from __future__ import annotations

import argparse
import re
import urllib.request
from pathlib import Path
from xml.sax.saxutils import quoteattr

ROOT = Path(__file__).resolve().parent.parent
REGISTER = "https://raw.githubusercontent.com/nebularis/lattice/refs/heads/main/docs/architecture/ontology-releases.md"
CATALOG = "https://raw.githubusercontent.com/nebularis/lattice/refs/heads/main/ontology/catalog-v001.xml"
EXTERNAL_RE = re.compile(r'<uri name="([^"]+)" uri="([a-z]+://[^"]+)"/>')
# | name | version | tag | <version IRI> | [label](url) · ... |
ROW_RE = re.compile(r"^\| ([a-z0-9-]+) \| (\d+)\.(\d+)\.(\d+) \| [^|]+ \| <([^>]+)> \| \[[^]]+\]\(([^)]+)\)")
ONTOLOGY_RE = re.compile(r"<([^>]+)>\s+(?:a|rdf:type)\s+owl:Ontology")


def read(location: str) -> str:
    if "://" in location:
        with urllib.request.urlopen(location) as response:
            return response.read().decode("utf-8")
    return Path(location).read_text(encoding="utf-8")


def lattice_entries(register: str) -> dict[str, str]:
    """Version IRI to raw URL for every released LATTICE document, and each
    ontology IRI to its latest release's URL."""
    entries, latest = {}, {}
    for line in read(register).splitlines():
        match = ROW_RE.match(line)
        if not match:
            continue
        name, *version, version_iri, url = match.groups()
        entries[version_iri] = url
        key = tuple(int(part) for part in version)
        if name not in latest or key > latest[name][0]:
            latest[name] = (key, url)
    for _, url in latest.values():
        ontology = ONTOLOGY_RE.search(read(url))
        if ontology:
            entries.setdefault(ontology.group(1), url)
    return entries


def local_entries(root: Path) -> dict[str, str]:
    entries = {}
    for path in sorted((root / "ontology").glob("*.ttl")):
        for iri in ONTOLOGY_RE.findall(path.read_text(encoding="utf-8")):
            entries[iri] = path.name
    return entries


def render(entries: dict[str, str]) -> str:
    lines = [f"    <uri name={quoteattr(name)} uri={quoteattr(uri)}/>" for name, uri in sorted(entries.items())]
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- SPDX-License-Identifier: MPL-2.0 -->\n"
        "<!-- Generated by tools/lattice_catalog.py. Do not edit by hand. -->\n"
        '<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">\n'
        + "\n".join(lines) + "\n</catalog>\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--register", default=REGISTER, help="LATTICE's ontology-releases.md, a URL or a path")
    parser.add_argument("--catalog", default=CATALOG, help="LATTICE's catalog, for its external imports")
    args = parser.parse_args(argv)
    local = local_entries(ROOT)
    lattice = dict(EXTERNAL_RE.findall(read(args.catalog)))
    lattice.update(lattice_entries(args.register))
    (ROOT / "ontology" / "catalog-v001.xml").write_text(render({**lattice, **local}), encoding="utf-8")
    print(f"ontology/catalog-v001.xml: {len(local)} Open CBAA and {len(lattice)} LATTICE and external entries")
    return 0


if __name__ == "__main__":
    assert ROW_RE.match("| foundation | 0.3.0 | foundation-v0.3.0 | <https://x/foundation/0.3.0> | [a.ttl](https://r/a.ttl) · [b](c) |")
    assert not ROW_RE.match("| foundation-shapes | 0.1.0 | foundation-shapes-v0.1.0 | none | [a.ttl](https://r/a.ttl) |")
    raise SystemExit(main())
